pymmcore-plus/useq-schema

- .pre-commit-config.yaml
- tests/test_sequence.py
- useq/_mda_sequence.py
At the moment, when there is _**no**_ `z_plan` (`NoZ`), when we set the stage to move and acquire images at different xy positions (e.g. through the `napari-micromanager` `mda` position table), the `z_pos` is always `None` even if it is defined in the experiment.
This PR fix this problem in the `iter_events` methods of the `MDASequence` class.
> fix: fix z_pos when there is no z_plan

- useq/_base_model.py
- useq/_channel.py
- useq/_mda_event.py
- useq/_mda_sequence.py
- useq/_position.py
- useq/_time.py
- useq/_utils.py
- useq/_z.py
This effectively makes all instances of MDASequence and MDAEvent frozen after creation.  They can be copied with modifications, but they can't be updated in place.  This is much safer inasmuch as these are objects that might be passed around to consumers (who could mutate state)
> feat: Make all models and fields frozen (except metadata)

- tests/test_sequence.py
- useq/_mda_sequence.py
- useq/_time.py
This removes the `order` argument from `MDASequence.iter_axes` and adds a new `replace` method that makes it easy to create a new instance of an MDA sequence with a single field replaced (since sequences are now frozen: #48)
It also adds an `MDASequence.used_axes` property that excludes axes with length zero.
so:
```python
In [13]: mda = MDASequence(
...:     time_plan={"interval": 0.1, "loops": 2},
...:     # stage_positions=[(1, 1, 1)],
...:     # z_plan={"range": 3, "step": 1},
...:     channels=[{"config": "DAPI", "exposure": 1}]
...: )
In [14]: mda.axis_order
Out[14]: 'tpcz'
In [15]: mda.shape
Out[15]: (2, 1)
In [16]: mda.used_axes
Out[16]: 'tc'
In [17]: mda.sizes
Out[17]: {'t': 2, 'p': 0, 'c': 1, 'z': 0}
```
To iterate with a different order, one should now:
```python
mda = …
```
> refactor: remove order from iter_axes

- .github/workflows/test_and_deploy.yml
- useq/_mda_event.py
- useq/_mda_sequence.py
Adds a global index to Event object, and `len` to a sequence object... So, given an Event object, you can now tell where you are in the experiment in two ways:
```python
mda = MDASequence(...)
In [11]: event.index
Out[11]: {'t': 0, 'p': 0, 'c': 0, 'z': 3}
In [12]: event.sequence.sizes
Out[12]: {'t': 2, 'p': 1, 'c': 1, 'z': 4}
In [13]: event.global_index
Out[13]: 3
In [14]: len(event.sequence)
Out[14]: 8
```
> feat: add global index to MDA Event and more docs

- src/useq/_tile.py
- tests/test_tile.py
in this PR:
- fix the  sign in `TileRelative` `_offset_y` method when `RelativeTo` is set to `center`.  If left negative, the grid is not calculated using the starting position as the center one.
- fix `TileFromCorners` so that the `corner` position are considered at the center of the image (and not at the top left corner).
- add specific tests for tiles.
> fix: fix TileRelative and TileFromCorners

- src/useq/_base_model.py
- src/useq/_mda_sequence.py
- tests/test_sequence.py
This PR would add a warning if someone uses an unrecognized keyword argument to any model:
```python
MDASequence(random_key='adsfomsadf')
```
we _could_ use `extra='forbid'`, but that raises an exception, which makes it hard to add new keys in the future without breaking backwards compatibility.
> feat: add warning on unused keys in valid object

- src/useq/__init__.py
- src/useq/_grid.py
- src/useq/_mda_sequence.py
- tests/test_grid.py
- tests/test_sequence.py
This PR updates the `GridFromCorners` object. Instead of setting up the grid bounding box using 2 coordinates (`corner1` and `corner2`), the grid is now defined by `top`, `left`, `bottom`, `right` `floats`.
> fix: update GridFromCorners with top, left, bottom, right floats

- src/useq/_mda_sequence.py
- tests/test_position_sequence.py
This PR fixes a bug in the `MDASequence` `iter_sequence` method and adds more tests.
Currently, if we run a sequence with multiple channels  and a grid_plan (or z_plan or time_plan) in a position sequence (like the one below), we get **ONLY ONE** channel through the sequence:
```py
mda = MDASequence(
channels=[
{"config": "Cy5", "exposure": 10},
{"config": "FITC", "exposure": 10}
],
stage_positions=[
{"x": 0, "y": 0, "sequence": {"grid_plan": {"rows": 2, "columns": 1}}}
]
)
```
running:
```py
for e in mda:
print(e.index)
```
current output:
``` py
{"p": 0, "c": 0, "g": 0}
{"p": 0, "c": 0, "g": 1}
```
with this fix, we get both the channels as expected:
```py
{"p": 0, "c": 0, "g": 0}
{"p": 0, "c": 0, "g": 1}
{"p": 0, "c": 1, "g": 0}
{"p": 0, "c": 1, "g": 1}
```
> fix: fix skip channel in iter_sequence + tests

- src/useq/_mda_sequence.py
This PR fixes an issue in the `MDASequence` `_check_order` methods. It prevents a `grid_plan` to be "validated" with the default for_size (1, 1) when not needed.
> fix: fix _check_order method

- src/useq/_mda_sequence.py
- tests/test_position_sequence.py
This PR fix a bug in the `MDASequence` `iter_sequence` method.
Currently, if we iter through a `MDASequence` where we specify `channels` (> 1) in the main sequence and `channel(s) + any plan` in the sub-sequence like the one below...
```py
mda = MDASequence(
axis_order="tpgcz",
channels=["Cy5", "FITC"],
stage_positions=[{"sequence": {"channels": ["DAPI"], "z_plan": {"range": 2, "step": 1}}}]
)
```
...we duplicate the number of events (duplication depends on the number of channels that are specified in the main sequence.). This is the current result:
```py
index: {'p': 0, 'c': 0, 'z': 0}  channel: DAPI
index: {'p': 0, 'c': 0, 'z': 1}  channel: DAPI
index: {'p': 0, 'c': 0, 'z': 2}  channel: DAPI
index: {'p': 0, 'c': 0, 'z': 0}  channel: DAPI
index: {'p': 0, 'c': 0, 'z': 1}  channel: DAPI …
```
> fix: MDASequence iter_sequence method

- src/useq/_channel.py
- src/useq/_mda_event.py
- src/useq/_mda_sequence.py
- tests/test_position_sequence.py
This simplifies the logic in `iter_sequence`, which has gotten a little hairy
> refactor: Simplify subsequence

- src/useq/_mda_sequence.py
- tests/test_autofocus.py
I found an `autofocus_plan` bug in the `MDASequence` `iter_sequence` method and this PR is a possible fix (also related to #97 ).
If we have a `MDASequence` with a position sub-sequence (like the one below)  where the `autofocus_plan` is *only* specified in the main sequence, the `autofocus_plan` should be also inherited by the position sub-sequence. However at the moment this does not happen.
```py
mda = MDASequence(
channels=["DAPI", "FITC"],
stage_positions=[(1, 2, 3),{"z": 10, "sequence":{"z_plan": {"range": 2, "step": 1}}}],
autofocus_plan={"autofocus_device_name": "Z", "autofocus_motor_offset": 40, "axes": ("z",)}
)
```
by printing index and action type
```
for e in mda:
print(e.index, e.action.type
```
we get
```
{'p': 0, 'c': 0} acquire_image
{'p': 0, 'c': 1} acquire_image
{'p': …
```
> fix: fix inherit sequence autofocus + add tests

- src/useq/_mda_sequence.py
- tests/test_sequence.py
this PR fixes a bug  in the `MDASequence` `_should_skip` method.
if we run this
```py
mda = MDASequence(channels=[{"config": "DAPI", "do_stack": False}])
assert len(list(mda)) == 1
```
we get a "z" KeyError because in the `_should_skip` method we don't make sure to also check for a `z_plan`
```py
if not channel.do_stack and index[Z] != len(z_plan) // 2:
return True
```
note: just switching from `index[Z]` to `index.get(Z)` does not work because the event will be skipped even when it shouldn't be.
> fix: KeyError fix in MDASequence _should_skip method

- src/useq/_mda_event.py
- tests/test_position_sequence.py
this PR changes the pattern used in test_position_sequence.  I find it's hard to figure out what went wrong when a test fails (you need to do a lot of visual comparison to see exactly what was different).  So this provides clearer error messages, and removes some boilerplate
> test: use different pattern for testing

- src/useq/_base_model.py
- src/useq/_mda_sequence.py
this moves the `replace` method to the frozen base model, and removes the kwargs from the signature
> refactor: move replace to FrozenModel

- pyproject.toml
- src/useq/__init__.py
- src/useq/_actions.py
- src/useq/_base_model.py
- src/useq/_channel.py
- src/useq/_hardware_autofocus.py
- src/useq/_mda_event.py
- src/useq/_mda_sequence.py
- src/useq/_position.py
- src/useq/_time.py
- src/useq/_z.py
among others, bans relative imports
> style: add a couple rules to ruff

- docs/schema/axes.md
- docs/schema/hardware_autofocus.md
> fix: remove NoX plans from docs

- .github/workflows/test_and_deploy.yml
failing until the `pymmcore-widgets` version without `NoX` plans is released.
> feat: add ci tests for pymmcore_widgets

- src/useq/_actions.py
- src/useq/_mda_event.py
- tests/test_sequence.py
cc @fdrgsp, 
I realized we do actually need to use Union types on MDAEvent.action.
this fixes it
> fix: change action type hint on MDAEvent 

- docs/index.md
- src/useq/_channel.py
- src/useq/_mda_event.py
We've been treating exposure everywhere (in pymmcore-plus) as if it's in milliseconds.  `core.setExposure` assumes milliseconds.  So this changes the docstring accordingly.  it's a "breaking" change but I doubt that anyone besides pymmcore plus  has been consuming this yet
> docs: update units of exposure in docstring to ms

- src/useq/_grid.py
- src/useq/_mda_sequence.py
This makes fov_width and height mutable (making them the only mutable fields in the schema).
The primary reason for this is so that pymmcore-plus engines can mutate fov sizes in place during setup_sequence.
> refactor: make fov_width/fov_height mutable on GridPlans

- src/useq/_iter_sequence.py
- src/useq/_mda_sequence.py
- tests/fixtures/mda.json
- tests/test_sequence.py
This is alternative to #97, that adds a `keep_shutter_open` logic to the MDA sequence.  The logic is described in the docstring:
> A tuple of axes `str` across which the illumination shutter should be kept open.
Resulting events will have `keep_shutter_open` set to `True` if and only if
ALL axes whose indices are changing are in this tuple. For example, if
`keep_shutter_open_across=('z',)`, then the shutter would be kept open between
events axes {'t': 0, 'z: 0} and {'t': 0, 'z': 1}, but not between
{'t': 0, 'z': 0} and {'t': 1, 'z': 0}.
closes #97 
closes #3
sidenote: this also opens up a possibility for a generalization of both this and autofocus plan, which would be general functions that take in the current event and (optionally) the upcoming event, and return either a modified current …
> feat: add `keep_shutter_open_across` to MDASequence

- .pre-commit-config.yaml
- pyproject.toml
- src/useq/__init__.py
- src/useq/_base_model.py
- src/useq/_grid.py
- src/useq/_hardware_autofocus.py
- src/useq/_iter_sequence.py
- src/useq/_mda_event.py
- src/useq/_mda_sequence.py
- src/useq/_pydantic_compat.py
- src/useq/_utils.py
- src/useq/_z.py
- tests/test_autofocus.py
- tests/test_misc.py
- tests/test_sequence.py
I pulled out most of the pydantic cross-compatibility stuff that I added in #122  (along with stuff I did for ome-types and psygnal), and make a new library: https://github.com/tlambert03/pydantic-compat
this PR uses it and pulls out most of the patch logic here
> build: use pydantic-compat library

- src/useq/_z.py
- tests/test_sequence.py
fixes a rounding issue when calculating the number of steps in a Zplan
> fix: fix rounding error in ZPlan num_positions estimate

- src/useq/_mda_event.py
- tests/test_sequence.py
```python
MDAEvent(channel="DAPI") == MDAEvent(channel={"config": "DAPI"})
```
> feat: accept bare string for mda event channel

- src/useq/_mda_sequence.py
> refactor: remove __str__ method on MDASequence

- src/useq/_mda_sequence.py
- tests/fixtures/mda.json
- tests/fixtures/mda.yaml
- tests/test_sequence.py
fixes #138 
Changes:
```python
MDASequence:
axis_order: str = "".join(AXES)
axis_order: Tuple[str, ...] = AXES
```
the typing of `MDASequence.axis_order` was too strict.  It's fine to accept a string as input, but it should also be able to accept a sequence of strings, each of which may be more than a single character
@ianhi, can you think of anywhere you're assuming axis_order is a literal string, rather than generic sequence of strings?
> refactor!: change axis_order type to `Tuple[str, ...]`

- pyproject.toml
> build: block pydantic2.4.1

- docs/schema/axes.md
- mkdocs.yml
- src/useq/_grid.py
Update the grid plans docstrings.
related to issue https://github.com/pymmcore-plus/useq-schema/issues/149
> fix: update docstrings grid plans

- .github/workflows/ci.yml
- .pre-commit-config.yaml
- README.md
- pyproject.toml
- src/useq/__init__.py
- src/useq/_base_model.py
- src/useq/_grid.py
- src/useq/_mda_event.py
- src/useq/_mda_sequence.py
- src/useq/_time.py
- src/useq/_utils.py
- src/useq/_z.py
- src/useq/pycromanager.py
- tests/fixtures/mda.yaml
- tests/test_misc.py
- tests/test_serialization.py
the primary reason to keep support for pydantic 1 was to play well with earlier versions of napari.  napari now at least supports being in the same environment as pydantic2, so let's just expect it
> build: drop support for pydantic 1

- src/useq/_grid.py
- src/useq/_plate.py
- src/useq/_position.py
- tests/test_grid.py
- tests/test_sequence.py
- tests/test_well_plate.py
@tlambert03 these are few updates I think might be useful. 
- add name to `GridPosition` + update `Position`
- make `well_size` required
- add docstrings
I also added a test to check the serialization because I was getting something weird when working on the `HCSWizard` widget. Basically if you create a `WellPlatePlan` from a `dict`, the `well_points_plan` is always `Position()` no matter what you pass and I don't yet understand why...
> feat: few updates for WellPlatePlan

- src/useq/_plate.py
- tests/test_well_plate.py
I think we needed to fix the unit of few methods of the `WellPlatePlan` since the `well_points_plan` and the stage coordinates are expressed in `µm` and the `WellPlate` in `mm`.
> fix: fix units for correct WellPlatePlan iteration

- src/useq/__init__.py
- src/useq/_base_model.py
- src/useq/_grid.py
- src/useq/_mda_sequence.py
- src/useq/_plate.py
- src/useq/_position.py
- tests/test_grid.py
This PR goes farther to formalize the relationship between all of the values in a `well_points_plan`,  namely, they are all `RelativeMultiPointPlan`  where
```python
RelativeMultiPointPlan = Union[
GridRowsColumns, GridWidthHeight, RandomPoints, RelativePosition
]
```
and they all support 
```python
def __iter__(self) -> Iterator[RelativePosition]: ...
def num_positions(self) -> int: ...
```
it also adds fov_height and width to the RelativePosition
> refactor: multi-point-plan

- .github/workflows/ci.yml
- pyproject.toml
- src/useq/_mda_sequence.py
found an issue with the smart union on `MDASequnce.grid_plan: MultiPointPlan` ... @fdrgsp, this may be related to the bug you were seeing ... but not sure.  it was working only on pydantic 2.8+
this should fix back to 2.2, and adds a tests for that
> fix: fix pydantic smart union in older versions, and add minreqs test

- src/useq/__init__.py
- src/useq/_grid.py
- src/useq/_mda_sequence.py
- src/useq/_plate.py
- src/useq/_plot.py
- src/useq/_point_visiting.py
- src/useq/_position.py
- tests/test_grid.py
- tests/test_points_plans.py
- tests/test_sequence.py
adds 
- useq.TraversalOrder - to dictate how random points are traversed
- addes a nearest neighbor and  2-opt algorithm, (for slightly better path choosing)
- allows you to specify the starting index
- adds plotting to all points plans:
```python
import useq
pp = useq.RandomPoints(
num_points=100,
max_height=6000,
max_width=6000,
order=useq.TraversalOrder.TWO_OPT,
random_seed=1,
shape="rectangle",
start_at=10,
fov_height=300,
fov_width=300,
allow_overlap=False,
)
pp.plot()
```
two-opt:
nearest neighbor:
> feat: formalizing point-visiting strategies

- src/useq/_base_model.py
- src/useq/_grid.py
this allows the start_at field of RandomPoints to be an actual position, with semantics:
```
start_at : int | RelativePosition
Position or index of the point to start at. This is only used if `order` is
'nearest_neighbor' or 'two_opt'.  If a position is provided, it will *always*
be included in the list of points. If an index is provided, it must be less than
the number of points, and corresponds to the index of the (randomly generated)
points; this likely only makes sense when `random_seed` is provided.
```
> feat: allow start_at to be a point

- src/useq/_plate.py
- tests/test_well_plate.py
This PR changes the two of `WellPlate.selected_wells` from the very lax IndexExpression
```python
Index = Union[int, List[int], Annotated[slice, _SliceType]]
IndexExpression = Union[Tuple[Index, ...], Index]
```
to a strict:
```python
Tuple[Tuple[int, ...], Tuple[int, ...]]
```
The primary reason is that it makes checking equality between two plate plans easier.
it also modifies `__repr_args__` to simplify the representation when possible
> refactor: normalize `WellPlate.selected_wells`

- .pre-commit-config.yaml
- src/useq/_plate.py
- tests/test_well_plate.py
this makes all "falsey" values to selected_wells in the WellPlatePlan imply no selected wells (rather than all selected wells)
> refactor: make None imply no selected wells

- src/useq/_mda_sequence.py
- tests/test_well_plate.py
make sure that passing a WellPlatePlan to MDASequence.stage_positions retains the proper type.  Useful for https://github.com/pymmcore-plus/pymmcore-widgets/pull/362
> fix: retain WellPlatePlan type when used for MDASequence.stage_positions

- src/useq/_iter_sequence.py
- tests/test_sequence.py
Fixes problem mentioned in #187. All events in sub-sequences had the reset_event_timer flag set to True.
https://github.com/pymmcore-plus/useq-schema/issues/187#issuecomment-2450480509
I'm not sure if this is the correct position for this fix, please check if this makes sense.
> fix: reset_event_timer defaults to True in sub-sequences

- .github/workflows/ci.yml
- src/useq/_grid.py
Pydantic 2.10 broke importing of useq-schema.  You'll see this error:
```python
.venv/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py:817: in _resolve_forward_ref
raise PydanticUndefinedAnnotation.from_name_error(e) from e
E   pydantic.errors.PydanticUndefinedAnnotation: name 'Annotated' is not defined
E
E   For further information visit https://errors.pydantic.dev/2.10/u/undefined-annotation
```
this PR fixes it, and should be released ASAP
> fix: fix for pydantic 2.10

- src/useq/_mda_event.py
- tests/test_sequence.py
closes #202 
- MDAEvent.slm_image is a new pydantic object SLMImage with two attributes (at the moment), data and device
- data is np.typing.ArrayLike (anything that can be case to a numpy array).  But for simplicity with pydantic, we type define it as `Any`.
- if device is None, it's up to the backend to pick the "current device"
- SLMImage is itself castable to a numpy array via `np.asarray(event.slm_image)`
- For now, I'm leaving all of the additional details that @hinderling mentioned in https://github.com/pymmcore-plus/useq-schema/issues/202#issuecomment-2490923194 (such as casting to different data types and dealing with device-specific on values) to backends like pymmcore[-plus]. 
```python
data = [[0, 0], [1, 1]]
event = MDAEvent(slm_image=data)
assert event.slm_image is not None …
```
> feat: add MDAEvent.slm_image

- .github/workflows/ci.yml
- pyproject.toml
- src/useq/_base_model.py
- src/useq/_grid.py
- src/useq/_hardware_autofocus.py
- src/useq/_iter_sequence.py
- src/useq/_mda_event.py
- src/useq/_mda_sequence.py
- src/useq/_plate.py
- src/useq/_plate_registry.py
- src/useq/_plot.py
- src/useq/_point_visiting.py
- src/useq/_position.py
- src/useq/_time.py
- src/useq/_z.py
- tests/test_autofocus.py
- tests/test_points_plans.py
- tests/test_position_sequence.py
- tests/test_sequence.py
> build: drop python 3.8

- .pre-commit-config.yaml
- pyproject.toml
- src/useq/__init__.py
- src/useq/_base_model.py
- src/useq/_iter_sequence.py
- src/useq/_mda_sequence.py
- tests/test_sequence.py
> fix: fix numpy arrays in repr

- src/useq/__init__.py
- src/useq/_actions.py
- src/useq/_mda_event.py
- tests/test_sequence.py
adds `useq.CustomAction`: an `Action` subclass that can be used to indicate any generic action.  This can represent anything, such as a fluidics event, or a photostimulation event, etc...  Data required to perform the action can be included in the `data` field, which is a dict.  user-provided `data` *must* be JSON-serializable, so as to avoid making the entire containing MDAEvent unserializable, and a ValidationError will be raised otherwise.  (Pydantic models may be use to capture complex things while retaining serialization)
this closes #213 - the fundamental need there was to allow for a way to indicate that `pymmcore-plus` should *never* try to perform hardware sequencing on a given event.  and this should accomplish this naturally (because pymmcore-plus already only tries to sequence …
> feat: add CustomAction - a generic container for data needed to execute any custom (non-acquisition) event

- src/useq/_grid.py
- tests/test_grid_and_points_plans.py
until a valid use case comes along, we disallow self-intersecting polygons during grid plan creation
> refactor: disallow self-intersecting GridFromPolygon
